 {{- if semverCompare "< 1.25-0" (include "carina.kubeVersion" .) -}}
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ .Values.node.name }}-psp
  labels:
    class: carina
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
    - 'SYS_ADMIN'
  fsGroup:
    rule: RunAsAny
  privileged: true
  hostNetwork: true
  hostPID: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'hostPath'
  allowedHostPaths:
    - pathPrefix: '/dev'
      readOnly: false
    - pathPrefix: '/run/mount'
      readOnly: false
    - pathPrefix: '/run/lvm'
      readOnly: false
    - pathPrefix: '/sys'
      readOnly: false
    - pathPrefix: '/var/log/carina'
      readOnly: false
    - pathPrefix: '/lib/modules'
      readOnly: false
    - pathPrefix: '/var/lib/kubelet/pods'
      readOnly: false
    - pathPrefix: '/var/lib/kubelet/plugins/csi.carina.com/'
      readOnly: false
    - pathPrefix: '/var/lib/kubelet/plugins_registry'
      readOnly: false
    - pathPrefix: '/var/lib/kubelet/plugins'
      readOnly: false
    - pathPrefix: '/var/lib/kubelet/device-plugins'
      readOnly: false

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.node.name }}
  # replace with non-default namespace name
  namespace: {{ .Release.Namespace }}
  labels:
    class: carina
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames: ['carina-csi-node-psp']

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.node.name }}
  # replace with non-default namespace name
  namespace: {{ .Release.Namespace }}
  labels:
    class: carina
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.node }}
    # replace with non-default namespace name
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.node.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
