{{- if .Values.storage.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-carina-raw
  namespace: {{ .Release.Namespace }}
provisioner: carina.storage.io
parameters:
  # file system
  csi.storage.k8s.io/fstype: {{ .Values.storage.raw.fstype }}
  # disk group
  carina.storage.io/disk-group-name: {{ .Values.storage.raw.disktype }}
reclaimPolicy: {{ .Values.storage.raw.reclaimPolicy }}
allowVolumeExpansion: true
# WaitForFirstConsumer表示被容器绑定调度后再创建pv
volumeBindingMode: {{ .Values.storage.raw.volumeBindingMode }}
mountOptions:
{{- end -}}
