apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  resourceName:  carina-scheduler
  resourceNamespace: kube-system
clientConnection:
  kubeconfig: /root/.kube/config
profiles:
  - schedulerName: carina-scheduler
    plugins:
      filter:
        enabled:
          - name: "local-storage"
            weight: 1
      score:
        enabled:
          - name: "local-storage"
            weight: 1
