---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.0
  creationTimestamp: null
  name: logicvolumes.carina.storage.io
spec:
  group: carina.storage.io
  names:
    kind: LogicVolume
    listKind: LogicVolumeList
    plural: logicvolumes
    shortNames:
      - lv
    singular: logicvolume
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .spec.size
          name: SIZE
          type: string
        - jsonPath: .spec.deviceGroup
          name: GROUP
          type: string
        - jsonPath: .spec.nodeName
          name: NODE
          type: string
        - jsonPath: .status.status
          name: STATUS
          type: string
        - jsonPath: .spec.nameSpace
          name: NAMESPACE
          priority: 1
          type: string
        - jsonPath: .spec.pvc
          name: PVC
          priority: 1
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: LogicVolume is the Schema for the logicvolumes API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: LogicVolumeSpec defines the desired state of LogicVolume
              properties:
                deviceGroup:
                  type: string
                nameSpace:
                  type: string
                nodeName:
                  description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                  type: string
                pvc:
                  type: string
                size:
                  anyOf:
                    - type: integer
                    - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
              required:
                - deviceGroup
                - nameSpace
                - nodeName
                - pvc
                - size
              type: object
            status:
              description: LogicVolumeStatus defines the observed state of LogicVolume
              properties:
                code:
                  description: A Code is an unsigned 32-bit error code as defined in
                    the gRPC spec.
                  format: int32
                  type: integer
                currentSize:
                  anyOf:
                    - type: integer
                    - type: string
                  pattern: ^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$
                  x-kubernetes-int-or-string: true
                deviceMajor:
                  format: int32
                  type: integer
                deviceMinor:
                  format: int32
                  type: integer
                message:
                  type: string
                status:
                  type: string
                volumeID:
                  description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
