---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-carina-raw-exclusivity
provisioner: carina.storage.io
parameters:
  # file system
  csi.storage.k8s.io/fstype: xfs
  # disk group
  carina.storage.io/disk-group-name: carina-raw
  carina.storage.io/exclusively-raw-disk: "true" 
reclaimPolicy: Delete
allowVolumeExpansion: true
# WaitForFirstConsumer表示被容器绑定调度后再创建pv
volumeBindingMode: WaitForFirstConsumer #Immediate 
mountOptions: